### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'const float' but got 'double'

### ISSUE THREAD

**Issue by Harmonyasha** [CyanChanges/python-dfpwm#2] opened 2024-03-30 23:17 UTC

**Comment by Harmonyasha** [comment] 2024-03-30 23:18
dfpwm = dfpwm.compressor(data)  # convert
            ^^^^^^^^^^^^^^^^^^^^^^
  File "dfpwm/convertor.pyx", line 68, in dfpwm.convertor.compressor      
    cpdef compressor(
  File "dfpwm/convertor.pyx", line 77, in dfpwm.convertor.compressor      
    cdef const float [:] in_array_view = in_array
ValueError: Buffer dtype mismatch, expected 'const float' but got 'double'

**Comment by iAmInActions** [comment] 2024-12-04 18:51
bump, can confirm, im on python 3.10.16, encountering the same issue running the provided example from this repository.

**Comment by CyanChanges** [comment] 2024-12-05 01:23
I'll look through this soon.

**Comment by CyanChanges** [comment] 2024-12-05 03:13
Should work now. Also added tests, passed lints.
Published 0.2.0.
Can you please to test those @Harmonyasha @iAmInActions

**Comment by CyanChanges** [comment] 2024-12-05 03:44
If the problem is resolved, I'll close the issue.

**Comment by CyanChanges** [comment] 2024-12-05 04:40
If it is still broken, please leave a comment. I will reopen

**Closed as completed by CyanChanges** 2024-12-05 04:40 UTC
